### ISSUE TITLE
Use a list of moons per constellation, rather than constellation per moon

### ISSUE THREAD

**Issue by Common-Say** [darmuh/LethalConstellations#2]
My modlist introduces a large amount of moons, and it would be much more convenient if I could specify which moon belongs to each constellation by typing out a comma-separated list, per constellation. Currently, I have to go into the config and change each moon's constellation value to the name of the constellation it belongs to.

**Comment by darmuh** [comment]
I'll have to think on this.

At the moment the config file is generated so that each moon is guaranteed a constellation outside of the ignore list. That is why it's specified on a per moon level based on what LLL designates as the numberless name

**Comment by darmuh** [comment]
> My modlist introduces a large amount of moons, and it would be much more convenient if I could specify which moon belongs to each constellation by typing out a comma-separated list, per constellation. Currently, I have to go into the config and change each moon's constellation value to the name of the constellation it belongs to.

Hello,

I've added this feature request in version 0.2.6. You can now use ``ManualSetupListing`` to manage moon/constellation mapping *before* there is a generated configuration item for the moon.

**Comment by Common-Say** [comment]
Thank you!
