### ISSUE TITLE
(Feature Request) - Randomize Starting Constellation Setting

### ISSUE THREAD

**Issue by EvolutioLunky** [darmuh/LethalConstellations#4]
### **Feature: Random Starting Constellation**
Saves start the ship in a random constellation from a starting pool. 
The starting pool will likely be decided by a config dependent blacklist.

**Comment by EvolutioLunky** [comment]
this would allow for users to create a more varied experience instead of going to the same 3 moons over and over.

**Comment by darmuh** [comment]
Hello,

I've added a portion of this feature request in version 0.2.6!

In the ``StartingConstellation`` config item, set it to ``~random~`` and your initial moon/constellation will be randomized 👍 

As for the starting pool, once I've verified there's no issues with the new StartingConstellation config item I will look into allowing for filtering for specific starting constellations :)

**Comment by darmuh** [comment]
Okay added the other portion of this request now in version 0.2.7 👍 

see below from changelog:

 - Added ``AcceptableStartingConstellations`` config item to set a specific set of constellations as potential starter constellations when ``StartingConstellation`` is set to ``~random~``.
	- Leave blank to let random choose ANY valid constellation
	- You can put duplicate entries of a constellation name to raise the odds that it will be chosen, this list does not need to have unique entries.
